### ISSUE TITLE
temporarily changing the version on the command line

### ISSUE THREAD

**Issue by NabiKAZ** [midnight-coding/WampServer-PHP-CLI-Version-Changer#3]
I think the possibility of temporarily changing the version on the command line can also be useful. That is, the registry does not change and is applied only temporarily and only for the same cmd window by change the PATH.

**Comment by custom-dev-tools** [comment]
Hi @NabiKAZ

If you are only wanting to change the PHP Version via a CLI then this script can do that as well.

See [this link here to the readme doc](https://github.com/custom-dev-tools/WampServer-PHP-CLI-Version-Changer#command-line-interface-cli)


---

Thank you for your suggestion.

It is a great idea if what you mean is `C:\> "C:\path\to\cli_changer.bat" php7.2.3 "C:\path\to\your_script.bat"`.

The CLI Changer Script could detect the paths currently set PHP version, update the path to the chosen PHP version, open up another CMD window and pass on your scripts path for it to run, and then when finished, rollback the path back to the previously set PHP version.

An event such as the closing of the second CMD window would need to be listened for to start the rollback.

For similar functionality now, you could:

1. Change the PHP version: `C:\>: "C:\path\to\cli_changer.bat" php7.2.3`
2. Call your batch script to run your task(s): `C:\>: "C:\path\to\your\script.bat"`
3. Rollback the PHP Version: `C:\>: "C:\path\to\cli_changer.bat" php7.1.0`

If this is a something you would do regularly then you could incorporate it all into a single script.

PS: I am not sure if being able to change the CMD windows PHP version number without changing the path is possible? Perhaps.

**Comment by NabiKAZ** [comment]
### About the idea you came up with...
This topic, although practical, was not exactly what I meant.
What you said about a `bat` script being called independently in a separate window is not very useful to me. But it can be done differently. For example, similar to what was done in `Python`.
In Python you can run a Python file as follows with two separate versions:
For version 2:
```
py -2 script.py
```
And for version 3:
```
py -3 script.py
```
So for php a similar run can be useful. For example:
```
cli_changer.bat -7.2.3 script.php
cli_changer.bat -7.1.0 script.php
```
A new window will not open and in the same window the script file will be executed and we will return to the command line with each version of the previous php (keep version of current environment).

### But about my previous idea...
But regardless of this idea, what I meant from the beginning was that, for example, I'm on the command line and 7.2.3 is active. I want to temporarily switch to 7.1.0 only in the same current window. But a change in the registry makes me go to this version forever and forget what my previous version was. So I just need to set this up:
`SET PATH=C:\wamp\bin\php\php7.1.0;%PATH%`
Without closing the window.
If a new window opens, the PATH and previous version of PHP 7.2.3 is still active.
look it for details:
```
C:\> php -v
PHP 7.2.3 (cli)...

C:\> cli_changer.bat 7.1.0 -current-environment
SET PATH=C:\wamp\bin\php\php7.1.0;%PATH%

C:\> php -v
PHP 7.1.0 (cli)...
```

Maybe merging these two ideas can be useful.

**Comment by custom-dev-tools** [comment]
Hi @NabiKAZ

Thank you for the reply.

I understand what you previously meant now. Thanks.

Unfortunately, when opening a "Microsoft Windows - Command Prompt Window", all environment paths, including the path to the PHP CLI are loaded and remain fixed within the open windows session and cannot be changed mid-session.

Changing the path to the PHP CLI will only be reflected within sessions of newly opened CMD windows.

For Example:

1. Open a CMD window and type `php -v`.
2. Run `cli_changer.bat` (Text Based User Interface will do) and select another PHP CLI version.
3. Now type `php -v` in the open CMD window again and you will notice that the PHP CLI version remains unchanged.
4. Now open a second (new) CMD window and type `php -v`. Only in this second window will you see the updated PHP CLI version.

This is a characteristic (and perhaps a limitation) of Microsoft CMD prompt windows.

The best one could hope for is similar to the initial interpretation of your Issue.

EG: Open a one-off CMD window with the temporary PHP version.
`C:\>: cli_changer.bat -temp php7.1.0`
Under the hood the script would open in a window, change the PHP CLI version, open a 2nd CMD window, then rollback the PHP CLI version and exit. The first window (used by the cli_changer.bat script) would flash on-screen for only a split-second. The  newly created (2nd) window would remain open for you to work with. Identifying the 2nd window with the temporary PHP version in the title bar would also be of benefit.

Would this be useful and a workable solution to you?

**Comment by NabiKAZ** [comment]
I know about needed open new cmd for effective, but we don't need new window, just can SET PATH for current environment window.
And all my target is didn't need to open any new window.

Maybe I can not express what I mean well. So I made a change in the code and submit [PR ](https://github.com/custom-dev-tools/WampServer-PHP-CLI-Version-Changer/pull/4)and you can see the code.
That's all I needed.

But there are a bug in [line #292](https://github.com/custom-dev-tools/WampServer-PHP-CLI-Version-Changer/pull/4/commits/809ebe49918dc09c233bc541ca117d8e82568155#diff-156e0ed18a0fbd502acad6b73a42c34c32d97850456be6a0d12e1a069da42e99R292) for now:
```BAT
rem Set path temporarily for current environment window.
REM TODO:
REM BUG: THIS SET PATH INTO SETLOCAL BLOCK AND NOT EFFECTIVE CURRENT ENVIRONMENT
REM      AND IF USE ENDLOCAL CAN NOT ACCESS TO VARIABLE SET OUTSIDE SETLOCAL
REM      SUMMARY, AT THE MOMENT, THE ONLY PROBLEM IS BECAUSE OF THE USE OF SETLOCAL
set PATH="%$usersEnvironmentalPathString%"
```

For use the new feature, Just try one of these:

```
cli_changer.bat php7.4.0 /temp
cli_changer.bat /temp
```

**Comment by custom-dev-tools** [comment]
Hi @NabiKAZ

I fully understand your request now that I see your use of the 'set path' command over the 'setx path' command. Sorry. I was a bit slow in not seeing your difference. IE: 'set' !== 'setx'

I did some CLI testing with 'set' and it looks very promising.

I think we will go with the following CLI signature:

`"C:\path\to\cli_changer.bat" php7.1.0 --temp`

I'll have a look at your PR and get back to you as soon as possible.

Thank you.

**Comment by NabiKAZ** [comment]
As for the switch, I used "/" because the switch is often Windows commands with "/" but Linux with "--". However, there is no sensitivity to this issue and it can be changed to "--" if you prefer.
Currently the main issue is the bug in using the "set" command.

**Comment by custom-dev-tools** [comment]
Hi @NabiKAZ

Just an update.

I've needed to make some major changes to the v1.2.3 code but it will be well worth the extra requested functionality. You pull request kicked me off in the right direction. CLI mode will provide feedback and exit codes should they be needed. All in all, it is coming along quite nicely.

![Screen Shot](https://user-images.githubusercontent.com/65024265/123776971-1ed7d780-d913-11eb-96f6-f7c67dfbefa0.png)

The [set]ting of the path outside the setlocal scope is achieved by:

`endlocal && set "Path=%$usersEnvironmentalPathString%" >nul`

That said, the `$usersEnvironmentalPathString` is lacking the system environment variables. When using `set path` to alter the sessions environmental variables, both the system environment variables and the user environment variables are combined into the one string.

As a result, all I need to work on now is exploding the `set path` variable, iterating through it to remove any reference of PHP versions, adding the 'temp' PHP version number, imploding it back together and finally [set]ting it. Shouldn't take to long to do though family and work commitments at the moment may delay me a little bit. All going well I should have it finished within the week.

I'll keep you updated.

**Comment by custom-dev-tools** [comment]
Hi @NabiKAZ

I have just pushed v1.3.0 to master.

I has been a bit of a major re-make so I didn't utilise your pull request. That said, thank you for submitting it.

I hope you enjoy the update.
